apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-minimal
  namespace: influx
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb:latest
        name: influxdb
        env:
          - name: INFLUXDB_GRAPHITE_ENABLED
            value: "true"
          - name: INFLUXDB_DB
            value: "iot"
        ports:
          - containerPort: 8086
            name: http
          - containerPort: 2003
            hostPort: 2003
        volumeMounts:
          - mountPath: /var/lib/influxdb
            name: kubedata
      volumes:
        - name: kubedata
          hostPath:
            path: /data/KubeData/influxdb
            type: DirectoryOrCreate